<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

Subsetting: Choosing elements from a list
Indexing: Choosing one specific element from a list
Slicing: Choosing a range of elements from a list
Masking	: Filtering out elements using a mask


In [ ]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_array_numbers = np_array_2d[:, 0]
np_array_int = np_array_numbers.astype(int)
mask = np_array_int%2 == 1
np_array_2d[mask, 1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

In [ ]:
py_list = [[66, 50, 57, -1, -1],
           [92, -1, 88, -1, -1],
           [75, -1, -1, 76, -1],
           [-1, 51, 87, -1, -1],
           [71, -1, 67, -1, 69]]

# Creating masks for <50, >50, ==50
np_array_2d = np.array(py_list)
np_array_neg1 = np_array_2d < 50
np_array_pos1 = np_array_2d > 50
np_array_0 = np_array_2d == 50

# Creating a 5x5 matrix of '0'
py_list_null = []
for i in range(5):
    py_list_null.append([0]*5)

'''
print(np_array_neg1)
print(np_array_pos1)
print(np_array_0)
'''

np_array_null = np.array(py_list_null)
np_array_2d = np_array_null + (-1 * np_array_neg1) + (np_array_pos1)
print(np_array_2d)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
